<h1 class="titulo_conteudo">Alteração de Projetos</h1>
<?php echo $this->teste; ?>
<div class="buscador">
    <form id="busca">
        
        <div class="unidade_busca">
            <label>Unidade</label>
            <br/>
            <?php echo $this->unidadeBusca; ?>
        </div>
        <div class="status_busca">
            <label>Status</label>
            <br/>
            <?php echo $this->statusBusca; ?>
        </div>
        <div class="botao_pesquisa">
            <?php echo $this->submitBusca; ?>
        </div>
    </form>
    <table id="tabela1" cellspacing="0" padding="0" border="1" class="display">
        <thead>
            <tr>
                <th>Status</th>
		<th>Unidade</th>
                <th>Título do Projeto</th>
                <th>Cliente</th>
                <th>SubProjeto FAI</th>	
            </tr>
        </thead>
         <?php echo $this->tabela; ?>
    </table>
</div>
<div class="linha_separadora"></div>
<form method="post" action="/alteracao">
    <br />
    <div id="status" class="margem">
        <label class="label">Status do Projeto</label>
        <br />
        <label class="sub_label">Escolha o status do projeto</label>
        <?php echo $this->status; ?>
    </div>
    <h4 class="separador margem" id="dados">Dados do Projeto</h4>
    <div id="dados_projeto" class="margem">
        <br/>
        <label class="label">Cliente</label>
        <br />
        <label class="sub_label">Insira o nome do cliente do projeto</label>
        <?php echo $this->cliente; ?>
        <br/>
        <label class="label">Título do Projeto</label>
        <br/>
        <label class="sub_label">Insira o título do projeto</label>
        <?php echo $this->tituloProjeto; ?>
        <br/>
        <div id="corrido">
            <div class="esquerda">
                <label class="label">SubProjeto FAI</label>
                <br/>
                <label class="sub_label">Insira o código do projeto na FAI</label>        
                <?php echo $this->subProjetoFAI;  ?>
            </div>
            <div class="direita">
                <label class="label">Unidade de Negócio</label>
               <br/>
               <label class="sub_label">Escolha a UN do CCDM que coordena o projeto</label>
               <?php echo $this->unidade; ?>
            </div>
        </div>
        <br/>
        <label class="label">Resumo do Projeto</label>
        <br/>
        <label class="sub_label">Insira o resumo do projeto</label>
        <?php echo $this->resumo; ?>
        <br/>
        <label class="label">Origem do(s) recurso(s)</label>
        <br/>
        <label class="sub_label">Insira a(s) fonte(s) dos recursos do projeto</label>
        <?php echo $this->origem; ?>
     </div>
    <h4 class="separador margem" id="prazos">Prazos</h4>
    <div id="prazos_div" class="margem">
        <br/>
        <div id="dataapp">
            <label class="label">Data de Aprovação</label>
            <br/>
            <label class="sub_label">Insira a data de aprovação do projeto</label>
            <?php echo $this->dataAprovacao; ?>
        </div>
        <div id="dataproj">
            <label class="label">Duração do Projeto (em meses)</label>
            <br/>
            <label class="sub_label">Insira a duração do projeto</label>
            <?php echo $this->duracaoProjeto; ?>
        </div>
        <div id="dataprevistainicio">
            <label class="label">Data Prevista de Início</label>
            <br/>
            <label class="sub_label">Insira a data prevista de início</label>
            <?php echo $this->dataPrevistaIni; ?>
        </div>
        <div id="dataprevistatermino">
            <label class="label">Data Prevista de Término</label>
            <br/>
            <label class="sub_label">Insira a data prevista de término</label>
            <?php echo $this->dataPrevistaTer; ?>
        </div>
    </div>
    <h4 class="separador margem" id="financeiro">Financeiro</h4>
    <div id="financeiro_div" class="margem">
        <label class="label">Valor proposto do projeto (em R$)</label>
        <br/>
        <label class="sub_label">Insira o valor total proposto para o projeto</label>
        <?php echo $this->valorProposto; ?>
        <br/>
        <br/>
        <label class="label">Valor Previsto de Investimento (em R$)</label>
        <br/>
        <label class="sub_label">Insira o valor total previsto de investimento</label>
        <?php echo $this->valorInvestimento; ?>
        <br/>
        <br/>
        <label class="label">Este projeto é ?</label>
        <?php echo $this->ProjetoServico; ?>
        <br/>
        <label class="label">Observações</label>
        <?php echo $this->ob; ?>  
    </div>
    <?php echo $this->submit; ?>
    <input type="hidden" name="id_altera" id="id_altera"/>
    <input type="hidden" name="mexeuValorProposto" value="0" />
    <input type="hidden" name="mexeuInvestimentoProposto" value="0"/>
</form>

