<nav>
    <ul>
        <li>
            <a href="/Index">Cadastro</a>
        </li>
        <li>
            <a href="/alteracao">Alteração</a>
        </li>
        <li>
            <a href="/acompanhamento">Acompanhamento</a>
        </li>
        <li>
            <a href="/relatorios">Relatórios</a>
        </li>
        <li>
            <a onclick="javascript:fechaa();">Sair</a>
        </li>
    </ul>
</nav>
